### PR TITLE
Fix cell resolution type

### LINKED ISSUE #7: cellResolutionType regex
Found during the live toolkit implementation:

```
[0]*[1-9][0-9]*\s[0]*[1-9][0-9]*
```

Seems to be a better representation

### PR DESCRIPTION
**Pull request by andreastai**
- The cell resolution type must allow leading zeros.

- The fix is based on the proposal by Zoltan Kozma.

- This fixes #7.

### CODE REVIEW

**Comment by andreastai** [comment]
@frans-ebu I can not request a review from @nigelmegitt or @EyalLevi. I can only request a review from EBU folks. Is there away to add members of the EBU working group?

**Comment by frans-ebu** [comment]
@tairt please try again. I changed the settings. I am not sure, but it seems the team admin access is not working as expected.

**Comment by nigelmegitt** [comment]
I've managed to add myself as a reviewer, so that seems to work. Thanks @frans-ebu .

**Review by nigelmegitt — APPROVED** [review]
Tested (manually) and works. Looks good to me.

**Comment by andreastai** [comment]
@frans-ebu I can add now @nigelmegitt as reviewer but not others. You may try it out with an issue. I can also assign it to people @nigelmegitt  and the EBU team.

**Pull request merged**
